// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tpcly.Lti.Samples.Spa.Data;

#nullable disable

namespace Tpcly.Lti.Samples.Spa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231002133448_AddLaunchSessions")]
    partial class AddLaunchSessions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tpcly.Lti.LaunchSession", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LtiStorageTarget")
                        .HasColumnType("longtext");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetLinkUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LaunchSessions");
                });

            modelBuilder.Entity("Tpcly.Lti.ToolPlatform", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccessTokenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AuthorizeUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JwkSetUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ToolPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
