# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Add source(s)
        run: dotnet nuget add source "https://nuget.pkg.github.com/Typiqally/index.json" --username Typiqally --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Add source(s)
        run: dotnet nuget add source "https://nuget.pkg.github.com/Typiqally/index.json" --username Typiqally --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
      - name: Restore dependencies
        run: dotnet restore
      # Create the NuGet package in the folder from the environment variable NuGetDirectory
      - run: dotnet pack --configuration Release --output ${{ github.workspace}}/nuget
      
      # Publish the NuGet package as an artifact, so they can be used in the following jobs
      - uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ github.workspace}}/nuget/*.nupkg
